/**
 * Embeddable context snippet for axis-toolbox
 * Generated by AXIS Toolbox
 * Drop this into any AI prompt to inject project context
 */

export const PROJECT_CONTEXT = {
  name: "axis-toolbox",
  type: "monorepo",
  language: "TypeScript",
  description: "AI-native development operating system. Upload or point at any codebase — get 86 generated artifacts across 18 specialized programs: context maps, debug playbooks, governance files, design tokens, SEO analysis, brand systems, and more.",
} as const;

export const CONVENTIONS = [
  "TypeScript strict mode",
  "pnpm workspaces",
] as const;

export const WARNINGS = [
] as const;

export const KEY_ABSTRACTIONS = [
  "apps/ (monorepo_apps)",
  "packages/ (monorepo_packages)",
  "payment-processing-output/ (project_directory)",
  "examples/ (project_directory)",
  "algorithmic/ (project_directory)",
  "artifacts/ (project_directory)",
  "brand/ (project_directory)",
  "canvas/ (project_directory)",
] as const;

/**
 * Inject into an AI prompt as a system-level context block.
 * Usage: embedProjectContext() returns a formatted string.
 */
export function embedProjectContext(): string {
  const sections = [
    `# Project: ${PROJECT_CONTEXT.name}`,
    `Type: ${PROJECT_CONTEXT.type} | Language: ${PROJECT_CONTEXT.language}`,
    `Description: ${PROJECT_CONTEXT.description}`,
    "",
    "## Conventions",
    ...CONVENTIONS.map(c => `- ${c}`),
    "",
    "## Warnings",
    ...WARNINGS.map(w => `- ${w}`),
    "",
    "## Key Abstractions",
    ...KEY_ABSTRACTIONS.map(a => `- ${a}`),
  ];
  return sections.join("\n");
}

export const ENTRY_POINTS = [
  { path: "apps/api/src/server.ts", exports: ["export const app = ..."] },
  { path: "apps/web/src/App.tsx", exports: ["export function App() { ... }"] },
  { path: "apps/web/src/main.tsx", exports: [] },
  { path: "packages/context-engine/src/index.ts", exports: ["export type { ... }","export { ... }"] },
  { path: "packages/generator-core/src/index.ts", exports: ["export type { ... }","export { ... }","export { ... }","export { ... }","export { ... }"] },
  { path: "packages/repo-parser/src/index.ts", exports: ["export type { ... }","export { ... }","export { ... }","export { ... }","export { ... }"] },
] as const;