/**
 * Generative Sketch — axis-toolbox
 * Algorithmic visualization of project structure
 * Generated by AXIS Toolbox
 */

interface Node {
  x: number;
  y: number;
  vx: number;
  vy: number;
  radius: number;
  hue: number;
  label: string;
}

interface Edge {
  from: number;
  to: number;
  weight: number;
}

const CONFIG = {
  width: 1920,
  height: 1080,
  nodeCount: 14,
  complexity: 0.01,
  palette: [{"name":"TypeScript","hue":220,"weight":70.9},{"name":"JSON","hue":280,"weight":10.5},{"name":"YAML","hue":340,"weight":9.1},{"name":"Markdown","hue":160,"weight":7.3},{"name":"JavaScript","hue":40,"weight":1.3}],
  dampening: 0.98,
  attractionStrength: 0.001,
  repulsionStrength: 500,
  edgeOpacity: 0.3,
};

function createNodes(): Node[] {
  const nodes: Node[] = [];
  for (let i = 0; i < CONFIG.nodeCount; i++) {
    const colorEntry = CONFIG.palette[i % CONFIG.palette.length];
    nodes.push({
      x: Math.random() * CONFIG.width,
      y: Math.random() * CONFIG.height,
      vx: (Math.random() - 0.5) * 2,
      vy: (Math.random() - 0.5) * 2,
      radius: 4 + Math.random() * (colorEntry.weight / 10),
      hue: colorEntry.hue + (Math.random() - 0.5) * 20,
      label: colorEntry.name,
    });
  }
  return nodes;
}

function createEdges(nodeCount: number): Edge[] {
  const edges: Edge[] = [];
  const edgeCount = Math.floor(nodeCount * CONFIG.complexity * 1.5);
  for (let i = 0; i < edgeCount; i++) {
    edges.push({
      from: Math.floor(Math.random() * nodeCount),
      to: Math.floor(Math.random() * nodeCount),
      weight: 0.5 + Math.random() * 0.5,
    });
  }
  return edges;
}

function simulate(nodes: Node[], edges: Edge[]) {
  // Repulsion between all nodes
  for (let i = 0; i < nodes.length; i++) {
    for (let j = i + 1; j < nodes.length; j++) {
      const dx = nodes[j].x - nodes[i].x;
      const dy = nodes[j].y - nodes[i].y;
      const dist = Math.sqrt(dx * dx + dy * dy) + 1;
      const force = CONFIG.repulsionStrength / (dist * dist);
      nodes[i].vx -= (dx / dist) * force;
      nodes[i].vy -= (dy / dist) * force;
      nodes[j].vx += (dx / dist) * force;
      nodes[j].vy += (dy / dist) * force;
    }
  }

  // Attraction along edges
  for (const edge of edges) {
    const a = nodes[edge.from];
    const b = nodes[edge.to];
    const dx = b.x - a.x;
    const dy = b.y - a.y;
    a.vx += dx * CONFIG.attractionStrength * edge.weight;
    a.vy += dy * CONFIG.attractionStrength * edge.weight;
    b.vx -= dx * CONFIG.attractionStrength * edge.weight;
    b.vy -= dy * CONFIG.attractionStrength * edge.weight;
  }

  // Update positions
  for (const node of nodes) {
    node.vx *= CONFIG.dampening;
    node.vy *= CONFIG.dampening;
    node.x += node.vx;
    node.y += node.vy;
    node.x = Math.max(node.radius, Math.min(CONFIG.width - node.radius, node.x));
    node.y = Math.max(node.radius, Math.min(CONFIG.height - node.radius, node.y));
  }
}

export function renderSketch(canvas: HTMLCanvasElement) {
  canvas.width = CONFIG.width;
  canvas.height = CONFIG.height;
  const ctx2d = canvas.getContext("2d")!;
  const nodes = createNodes();
  const edges = createEdges(nodes.length);

  function frame() {
    simulate(nodes, edges);
    ctx2d.fillStyle = "rgba(15, 23, 42, 0.1)";
    ctx2d.fillRect(0, 0, CONFIG.width, CONFIG.height);

    // Draw edges
    for (const edge of edges) {
      const a = nodes[edge.from];
      const b = nodes[edge.to];
      ctx2d.strokeStyle = `hsla(${a.hue}, 60%, 60%, ${CONFIG.edgeOpacity * edge.weight})`;
      ctx2d.lineWidth = edge.weight;
      ctx2d.beginPath();
      ctx2d.moveTo(a.x, a.y);
      ctx2d.lineTo(b.x, b.y);
      ctx2d.stroke();
    }

    // Draw nodes
    for (const node of nodes) {
      ctx2d.fillStyle = `hsl(${node.hue}, 70%, 60%)`;
      ctx2d.beginPath();
      ctx2d.arc(node.x, node.y, node.radius, 0, Math.PI * 2);
      ctx2d.fill();
    }

    requestAnimationFrame(frame);
  }

  frame();
}

export { CONFIG, createNodes, createEdges, simulate };

// ─── Source File Tree ──────────────────────────────────
// .
// g
// i
// t
// h
// u
// b
// /
// w
// o
// r
// k
// f
// l
// o
// w
// s
// /
// c
// i