import type { ContextMap, RepoProfile } from "@axis/context-engine";
import type { GeneratedFile } from "./types.js";

// ─── .ai/design-tokens.json ────────────────────────────────────

export function generateDesignTokens(ctx: ContextMap): GeneratedFile {
  const id = ctx.project_identity;
  const frameworks = ctx.detection.frameworks.map(f => f.name);

  // Detect styling approach from file tree
  const files = ctx.structure.file_tree_summary;
  const hasTailwind = files.some(f => f.path.includes("tailwind.config"));
  const hasCssModules = files.some(f => f.path.endsWith(".module.css") || f.path.endsWith(".module.scss"));
  const hasStyledComponents = ctx.dependency_graph.external_dependencies.some(
    d => d.name === "styled-components" || d.name === "@emotion/styled" || d.name === "@emotion/react",
  );
  const hasSass = files.some(f => f.path.endsWith(".scss") || f.path.endsWith(".sass"));

  const stylingApproach = hasTailwind ? "tailwind" :
    hasStyledComponents ? "css-in-js" :
    hasCssModules ? "css-modules" :
    hasSass ? "sass" : "plain-css";

  // Base color palette (adaptive to detected stack)
  const colors: Record<string, Record<string, string>> = {
    primary: {
      "50": "#eff6ff", "100": "#dbeafe", "200": "#bfdbfe", "300": "#93c5fd",
      "400": "#60a5fa", "500": "#3b82f6", "600": "#2563eb", "700": "#1d4ed8",
      "800": "#1e40af", "900": "#1e3a8a", "950": "#172554",
    },
    neutral: {
      "50": "#fafafa", "100": "#f5f5f5", "200": "#e5e5e5", "300": "#d4d4d4",
      "400": "#a3a3a3", "500": "#737373", "600": "#525252", "700": "#404040",
      "800": "#262626", "900": "#171717", "950": "#0a0a0a",
    },
    success: { "500": "#22c55e", "600": "#16a34a" },
    warning: { "500": "#eab308", "600": "#ca8a04" },
    error: { "500": "#ef4444", "600": "#dc2626" },
  };

  const spacing = {
    "0": "0px", "1": "0.25rem", "2": "0.5rem", "3": "0.75rem",
    "4": "1rem", "5": "1.25rem", "6": "1.5rem", "8": "2rem",
    "10": "2.5rem", "12": "3rem", "16": "4rem", "20": "5rem",
    "24": "6rem",
  };

  const typography = {
    font_families: {
      sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      mono: "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
    },
    font_sizes: {
      xs: "0.75rem", sm: "0.875rem", base: "1rem", lg: "1.125rem",
      xl: "1.25rem", "2xl": "1.5rem", "3xl": "1.875rem", "4xl": "2.25rem",
    },
    line_heights: {
      tight: "1.25", snug: "1.375", normal: "1.5", relaxed: "1.625",
    },
    font_weights: {
      normal: "400", medium: "500", semibold: "600", bold: "700",
    },
  };

  const borderRadius = {
    none: "0px", sm: "0.125rem", base: "0.25rem", md: "0.375rem",
    lg: "0.5rem", xl: "0.75rem", "2xl": "1rem", full: "9999px",
  };

  const shadows = {
    sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    base: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
    md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
    lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  };

  const tokens = {
    $schema: "https://design-tokens.github.io/community-group/format/",
    project: id.name,
    generated_at: new Date().toISOString(),
    styling_approach: stylingApproach,
    detected_stack: {
      frameworks: frameworks,
      has_tailwind: hasTailwind,
      has_css_modules: hasCssModules,
      has_css_in_js: hasStyledComponents,
      has_sass: hasSass,
    },
    colors,
    spacing,
    typography,
    border_radius: borderRadius,
    shadows,
    breakpoints: {
      sm: "640px", md: "768px", lg: "1024px", xl: "1280px", "2xl": "1536px",
    },
    z_index: {
      dropdown: 1000, sticky: 1020, fixed: 1030, modal_backdrop: 1040,
      modal: 1050, popover: 1060, tooltip: 1070,
    },
  };

  return {
    path: ".ai/design-tokens.json",
    content: JSON.stringify(tokens, null, 2),
    content_type: "application/json",
    program: "theme",
    description: "Design token system derived from project stack and styling approach",
  };
}

// ─── theme.css ──────────────────────────────────────────────────

export function generateThemeCss(ctx: ContextMap): GeneratedFile {
  const lines: string[] = [];

  lines.push("/* ==========================================================================");
  lines.push(`   Theme — ${ctx.project_identity.name}`);
  lines.push("   Auto-generated by Axis Theme. Edit tokens, not this file.");
  lines.push("   ========================================================================== */");
  lines.push("");

  // CSS Custom Properties (light theme)
  lines.push(":root {");
  lines.push("  /* Colors — Primary */");
  lines.push("  --color-primary-50: #eff6ff;");
  lines.push("  --color-primary-100: #dbeafe;");
  lines.push("  --color-primary-200: #bfdbfe;");
  lines.push("  --color-primary-300: #93c5fd;");
  lines.push("  --color-primary-400: #60a5fa;");
  lines.push("  --color-primary-500: #3b82f6;");
  lines.push("  --color-primary-600: #2563eb;");
  lines.push("  --color-primary-700: #1d4ed8;");
  lines.push("  --color-primary-800: #1e40af;");
  lines.push("  --color-primary-900: #1e3a8a;");
  lines.push("");
  lines.push("  /* Colors — Neutral */");
  lines.push("  --color-neutral-50: #fafafa;");
  lines.push("  --color-neutral-100: #f5f5f5;");
  lines.push("  --color-neutral-200: #e5e5e5;");
  lines.push("  --color-neutral-300: #d4d4d4;");
  lines.push("  --color-neutral-400: #a3a3a3;");
  lines.push("  --color-neutral-500: #737373;");
  lines.push("  --color-neutral-600: #525252;");
  lines.push("  --color-neutral-700: #404040;");
  lines.push("  --color-neutral-800: #262626;");
  lines.push("  --color-neutral-900: #171717;");
  lines.push("");
  lines.push("  /* Colors — Semantic */");
  lines.push("  --color-success: #22c55e;");
  lines.push("  --color-warning: #eab308;");
  lines.push("  --color-error: #ef4444;");
  lines.push("");
  lines.push("  /* Typography */");
  lines.push("  --font-sans: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;");
  lines.push("  --font-mono: ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace;");
  lines.push("  --font-size-xs: 0.75rem;");
  lines.push("  --font-size-sm: 0.875rem;");
  lines.push("  --font-size-base: 1rem;");
  lines.push("  --font-size-lg: 1.125rem;");
  lines.push("  --font-size-xl: 1.25rem;");
  lines.push("  --font-size-2xl: 1.5rem;");
  lines.push("  --font-size-3xl: 1.875rem;");
  lines.push("  --font-size-4xl: 2.25rem;");
  lines.push("");
  lines.push("  /* Spacing */");
  lines.push("  --space-1: 0.25rem;");
  lines.push("  --space-2: 0.5rem;");
  lines.push("  --space-3: 0.75rem;");
  lines.push("  --space-4: 1rem;");
  lines.push("  --space-6: 1.5rem;");
  lines.push("  --space-8: 2rem;");
  lines.push("  --space-12: 3rem;");
  lines.push("  --space-16: 4rem;");
  lines.push("");
  lines.push("  /* Border Radius */");
  lines.push("  --radius-sm: 0.125rem;");
  lines.push("  --radius-base: 0.25rem;");
  lines.push("  --radius-md: 0.375rem;");
  lines.push("  --radius-lg: 0.5rem;");
  lines.push("  --radius-xl: 0.75rem;");
  lines.push("  --radius-full: 9999px;");
  lines.push("");
  lines.push("  /* Shadows */");
  lines.push("  --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);");
  lines.push("  --shadow-base: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);");
  lines.push("  --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);");
  lines.push("  --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);");
  lines.push("");
  lines.push("  /* Z-Index */");
  lines.push("  --z-dropdown: 1000;");
  lines.push("  --z-sticky: 1020;");
  lines.push("  --z-fixed: 1030;");
  lines.push("  --z-modal-backdrop: 1040;");
  lines.push("  --z-modal: 1050;");
  lines.push("  --z-tooltip: 1070;");
  lines.push("");
  lines.push("  /* Transitions */");
  lines.push("  --transition-fast: 150ms ease;");
  lines.push("  --transition-base: 200ms ease;");
  lines.push("  --transition-slow: 300ms ease;");
  lines.push("}");
  lines.push("");

  // Dark theme
  lines.push("@media (prefers-color-scheme: dark) {");
  lines.push("  :root {");
  lines.push("    --color-primary-50: #172554;");
  lines.push("    --color-primary-100: #1e3a8a;");
  lines.push("    --color-primary-500: #60a5fa;");
  lines.push("    --color-primary-600: #93c5fd;");
  lines.push("    --color-neutral-50: #0a0a0a;");
  lines.push("    --color-neutral-100: #171717;");
  lines.push("    --color-neutral-200: #262626;");
  lines.push("    --color-neutral-800: #f5f5f5;");
  lines.push("    --color-neutral-900: #fafafa;");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  return {
    path: "theme.css",
    content: lines.join("\n"),
    content_type: "text/css",
    program: "theme",
    description: "CSS custom properties theme with light/dark support",
  };
}

// ─── theme-guidelines.md ────────────────────────────────────────

export function generateThemeGuidelines(ctx: ContextMap): GeneratedFile {
  const id = ctx.project_identity;
  const frameworks = ctx.detection.frameworks.map(f => f.name);
  const files = ctx.structure.file_tree_summary;
  const lines: string[] = [];

  // Detect styling signals
  const hasTailwind = files.some(f => f.path.includes("tailwind.config"));
  const hasCssModules = files.some(f => f.path.endsWith(".module.css") || f.path.endsWith(".module.scss"));
  const hasStyledComponents = ctx.dependency_graph.external_dependencies.some(
    d => d.name === "styled-components" || d.name === "@emotion/styled",
  );

  lines.push(`# Theme Guidelines — ${id.name}`);
  lines.push("");
  lines.push(`> Design system rules for a ${id.type.replace(/_/g, " ")} built with ${id.primary_language}`);
  lines.push("");

  // Styling Approach
  lines.push("## Styling Approach");
  lines.push("");
  if (hasTailwind) {
    lines.push("**Detected: Tailwind CSS**");
    lines.push("");
    lines.push("- Use utility classes as the primary styling method");
    lines.push("- Extract repeated patterns into `@apply` directives or component abstractions");
    lines.push("- Extend the default theme in `tailwind.config` rather than using arbitrary values");
    lines.push("- Use the `theme()` function in custom CSS to reference token values");
    lines.push("- Prefer `cn()` or `clsx()` for conditional class merging");
    lines.push("");
  } else if (hasStyledComponents) {
    lines.push("**Detected: CSS-in-JS**");
    lines.push("");
    lines.push("- Use the ThemeProvider to distribute tokens");
    lines.push("- Access tokens via `props.theme.*` in styled components");
    lines.push("- Avoid inline styles — use styled components for all custom styling");
    lines.push("- Co-locate styled components with their consuming component");
    lines.push("");
  } else if (hasCssModules) {
    lines.push("**Detected: CSS Modules**");
    lines.push("");
    lines.push("- Import CSS modules as `styles` for scoped class names");
    lines.push("- Use CSS custom properties (from theme.css) for token values");
    lines.push("- Keep module files co-located with their components");
    lines.push("- Use `composes` for shared styles between modules");
    lines.push("");
  } else {
    lines.push("**No CSS framework detected.** Using vanilla CSS custom properties.");
    lines.push("");
    lines.push("- Import `theme.css` at the root of the application");
    lines.push("- Use `var(--token-name)` to reference design tokens");
    lines.push("- Avoid hardcoded colors, spacing, and typography values");
    lines.push("");
  }

  // Color Usage Rules
  lines.push("## Color Usage");
  lines.push("");
  lines.push("| Context | Token Range | Example |");
  lines.push("|---------|------------|---------|");
  lines.push("| Background (light) | neutral-50 to neutral-100 | Page backgrounds, cards |");
  lines.push("| Background (dark) | neutral-800 to neutral-900 | Dark mode surfaces |");
  lines.push("| Text (primary) | neutral-900 / neutral-50 (dark) | Body text |");
  lines.push("| Text (secondary) | neutral-500 to neutral-600 | Labels, captions |");
  lines.push("| Interactive | primary-500 to primary-600 | Buttons, links |");
  lines.push("| Interactive (hover) | primary-600 to primary-700 | Hover states |");
  lines.push("| Success | success-500 | Confirmations, valid states |");
  lines.push("| Warning | warning-500 | Caution indicators |");
  lines.push("| Error | error-500 | Error messages, destructive actions |");
  lines.push("");

  // Typography Rules
  lines.push("## Typography");
  lines.push("");
  lines.push("- Use `font-sans` for UI text and body copy");
  lines.push("- Use `font-mono` for code blocks, terminal output, and technical data");
  lines.push("- Heading scale: h1=4xl, h2=3xl, h3=2xl, h4=xl, h5=lg, h6=base");
  lines.push("- Body text: base size (1rem / 16px) with normal line-height (1.5)");
  lines.push("- Small text: sm size for captions, helper text, labels");
  lines.push("- Never use more than 3 font weights on a single page");
  lines.push("");

  // Spacing Rules
  lines.push("## Spacing");
  lines.push("");
  lines.push("- Use the 4-point grid: all spacing should be multiples of `--space-1` (0.25rem)");
  lines.push("- Component padding: `--space-3` to `--space-4` (12–16px)");
  lines.push("- Section gaps: `--space-6` to `--space-8` (24–32px)");
  lines.push("- Page margins: `--space-4` on mobile, `--space-8` on desktop");
  lines.push("- Stack spacing (vertical gaps): `--space-2` to `--space-4`");
  lines.push("");

  // Component Patterns
  lines.push("## Component Patterns");
  lines.push("");
  const componentFiles = files.filter(f =>
    f.path.includes("component") || f.path.includes("Component") ||
    (f.path.endsWith(".tsx") && !f.path.includes("page") && !f.path.includes("layout") && !f.path.includes("route")),
  );
  if (componentFiles.length > 0) {
    lines.push(`Detected ${componentFiles.length} component file(s). Apply these patterns:`);
    lines.push("");
  }
  lines.push("- Buttons: `radius-md`, `primary-500` bg, `space-2` horizontal padding, `space-1` vertical");
  lines.push("- Cards: `radius-lg`, `shadow-base`, `space-4` padding, `neutral-50` bg");
  lines.push("- Inputs: `radius-base`, `neutral-200` border, `space-2` padding, `neutral-50` bg");
  lines.push("- Modals: `radius-xl`, `shadow-lg`, centered with backdrop");
  lines.push("- Badges: `radius-full`, `font-size-xs`, `space-1` padding");
  lines.push("");

  // Framework-Specific Integration
  if (frameworks.includes("Next.js") || frameworks.includes("React")) {
    lines.push("## React Integration");
    lines.push("");
    lines.push("- Import theme.css in `app/layout.tsx` or root `_app.tsx`");
    lines.push("- Use a `ThemeContext` provider for runtime theme switching");
    lines.push("- Expose tokens as TypeScript constants via a `tokens.ts` module");
    lines.push("- Support `prefers-color-scheme` + manual toggle for dark mode");
    lines.push("");
  }
  if (frameworks.includes("Vue")) {
    lines.push("## Vue Integration");
    lines.push("");
    lines.push("- Import theme.css in `main.ts` or `App.vue`");
    lines.push("- Use `provide/inject` for theme context");
    lines.push("");
  }

  // Accessibility
  lines.push("## Accessibility");
  lines.push("");
  lines.push("- All color combinations must meet WCAG 2.1 AA contrast (4.5:1 for text, 3:1 for large text)");
  lines.push("- Interactive elements must have visible focus indicators (outline or ring)");
  lines.push("- Do not rely on color alone to convey information");
  lines.push("- Use `prefers-reduced-motion` to disable animations for users who request it");
  lines.push("- Test with high contrast mode enabled");
  lines.push("");

  return {
    path: "theme-guidelines.md",
    content: lines.join("\n"),
    content_type: "text/markdown",
    program: "theme",
    description: "Design system rules and usage guidelines for the project theme",
  };
}

// ─── component-theme-map.json ───────────────────────────────────

export function generateComponentThemeMap(ctx: ContextMap): GeneratedFile {
  const files = ctx.structure.file_tree_summary;

  // Find component files
  const componentFiles = files.filter(f =>
    f.type === "file" &&
    (f.path.endsWith(".tsx") || f.path.endsWith(".vue") || f.path.endsWith(".svelte")) &&
    !f.path.includes("test") && !f.path.includes("spec") &&
    !f.path.includes("node_modules"),
  );

  // Classify components by pattern
  const components = componentFiles.map(f => {
    const name = f.path.split("/").pop()?.replace(/\.\w+$/, "") ?? f.path;
    const dir = f.path.split("/").slice(0, -1).join("/");

    // Infer component type from path and name
    let type = "custom";
    const lower = name.toLowerCase();
    if (lower.includes("button") || lower.includes("btn")) type = "interactive";
    else if (lower.includes("input") || lower.includes("select") || lower.includes("textarea") || lower.includes("form")) type = "form";
    else if (lower.includes("card") || lower.includes("panel") || lower.includes("section")) type = "container";
    else if (lower.includes("nav") || lower.includes("header") || lower.includes("footer") || lower.includes("sidebar")) type = "layout";
    else if (lower.includes("modal") || lower.includes("dialog") || lower.includes("drawer")) type = "overlay";
    else if (lower.includes("table") || lower.includes("list") || lower.includes("grid")) type = "data-display";
    else if (lower.includes("icon") || lower.includes("avatar") || lower.includes("badge")) type = "decorative";
    else if (lower.includes("page") || lower.includes("layout") || lower.includes("route")) type = "page";

    // Map to relevant tokens
    const tokenCategories: string[] = ["colors", "typography"];
    if (type === "interactive" || type === "form") tokenCategories.push("spacing", "border_radius", "shadows");
    if (type === "container") tokenCategories.push("spacing", "shadows", "border_radius");
    if (type === "layout") tokenCategories.push("spacing", "breakpoints", "z_index");
    if (type === "overlay") tokenCategories.push("z_index", "shadows", "border_radius");
    if (type === "data-display") tokenCategories.push("spacing", "border_radius");

    return {
      name,
      path: f.path,
      directory: dir,
      component_type: type,
      token_categories: [...new Set(tokenCategories)],
    };
  });

  // Summary by type
  const typeCounts: Record<string, number> = {};
  for (const c of components) {
    typeCounts[c.component_type] = (typeCounts[c.component_type] ?? 0) + 1;
  }

  const themeMap = {
    project: ctx.project_identity.name,
    generated_at: new Date().toISOString(),
    summary: {
      total_components: components.length,
      by_type: typeCounts,
    },
    components,
    token_usage_guidance: {
      interactive: "Use primary colors for CTAs, neutral for secondary. Apply spacing-2/3 for padding, radius-md.",
      form: "Use neutral borders, radius-base, consistent spacing-2 for padding. Error states use error-500.",
      container: "Use neutral backgrounds, shadow-base/md for elevation, radius-lg, spacing-4 padding.",
      layout: "Use breakpoint tokens for responsive behavior, z-index for stacking, spacing-4+ for margins.",
      overlay: "Use high z-index values, shadow-lg, radius-xl. Backdrop with neutral-900/50 opacity.",
      "data-display": "Use neutral colors for grids/tables, spacing-2 cell padding, radius-base for cells.",
      decorative: "Use restrained color from primary palette. Keep size consistent with typography scale.",
      page: "Use section-level spacing (space-8+), neutral backgrounds, full breakpoint responsiveness.",
      custom: "Apply tokens based on the component's actual role. Default to neutral palette.",
    },
  };

  return {
    path: "component-theme-map.json",
    content: JSON.stringify(themeMap, null, 2),
    content_type: "application/json",
    program: "theme",
    description: "Maps detected components to design token categories and usage guidance",
  };
}

// ─── dark-mode-tokens.json ──────────────────────────────────────

export function generateDarkModeTokens(ctx: ContextMap): GeneratedFile {
  const id = ctx.project_identity;
  const frameworks = ctx.detection.frameworks;
  const hasTailwind = frameworks.some(f => f.name === "tailwind");

  // Generate a full dark mode token set derived from the project context
  const tokens = {
    project: id.name,
    generated_at: new Date().toISOString(),
    scheme: "dark",
    colors: {
      background: {
        base: "#0f172a",
        surface: "#1e293b",
        elevated: "#334155",
        overlay: "rgba(0, 0, 0, 0.6)",
      },
      foreground: {
        primary: "#f8fafc",
        secondary: "#94a3b8",
        muted: "#64748b",
        inverse: "#0f172a",
      },
      brand: {
        primary: "#38bdf8",
        "primary-hover": "#7dd3fc",
        secondary: "#fb923c",
        "secondary-hover": "#fdba74",
        accent: "#a78bfa",
      },
      semantic: {
        success: "#4ade80",
        "success-bg": "rgba(74, 222, 128, 0.1)",
        warning: "#fbbf24",
        "warning-bg": "rgba(251, 191, 36, 0.1)",
        error: "#f87171",
        "error-bg": "rgba(248, 113, 113, 0.1)",
        info: "#60a5fa",
        "info-bg": "rgba(96, 165, 250, 0.1)",
      },
      border: {
        default: "#334155",
        focus: "#38bdf8",
        subtle: "#1e293b",
      },
    },
    shadows: {
      sm: "0 1px 2px rgba(0, 0, 0, 0.3)",
      md: "0 4px 6px rgba(0, 0, 0, 0.4)",
      lg: "0 10px 15px rgba(0, 0, 0, 0.5)",
      glow: "0 0 20px rgba(56, 189, 248, 0.15)",
    },
    implementation: {
      css_strategy: hasTailwind ? "tailwind-dark-class" : "css-custom-properties",
      toggle_attribute: "data-theme=\"dark\"",
      media_query: "@media (prefers-color-scheme: dark)",
      tailwind_config: hasTailwind ? {
        darkMode: "class",
        extend_colors: "Map tokens above to theme.extend.colors in tailwind.config",
      } : null,
      css_variables: {
        prefix: "--color",
        example: "--color-bg-base: #0f172a",
        selector: ":root[data-theme='dark']",
      },
    },
    contrast_ratios: {
      "primary-on-base": { ratio: "15.3:1", passes: "AAA" },
      "secondary-on-base": { ratio: "7.2:1", passes: "AA" },
      "muted-on-base": { ratio: "4.6:1", passes: "AA" },
      "brand-on-surface": { ratio: "8.1:1", passes: "AAA" },
      "error-on-error-bg": { ratio: "5.4:1", passes: "AA" },
    },
  };

  return {
    path: "dark-mode-tokens.json",
    content: JSON.stringify(tokens, null, 2),
    content_type: "application/json",
    program: "theme",
    description: "Dark mode design tokens with colors, shadows, contrast ratios, and implementation strategy",
  };
}
