import type { ContextMap, RepoProfile } from "@axis/context-engine";
import type { GeneratedFile, SourceFile } from "./types.js";
import { hasFw, getFw } from "./fw-helpers.js";
import { findFiles, fileTree } from "./file-excerpt-utils.js";

// ─── generative-sketch.ts ───────────────────────────────────────

export function generateGenerativeSketch(ctx: ContextMap, files?: SourceFile[]): GeneratedFile {
  const id = ctx.project_identity;
  const languages = ctx.detection.languages;
  const patterns = ctx.architecture_signals.patterns_detected;
  const hotspots = ctx.dependency_graph.hotspots;

  // Derive visual parameters from project data
  const nodeCount = Math.max(5, Math.min(50, ctx.entry_points.length * 3 + hotspots.length * 2));
  const complexity = Math.min(1, ctx.architecture_signals.separation_score / 100);
  const langColors = languages.slice(0, 5).map((l, i) => {
    const hues = [220, 280, 340, 160, 40];
    return { name: l.name, hue: hues[i % hues.length], weight: l.loc_percent };
  });

  const lines: string[] = [];

  lines.push("/**");
  lines.push(` * Generative Sketch — ${id.name}`);
  lines.push(" * Algorithmic visualization of project structure");
  lines.push(" * Generated by AXIS Toolbox");
  lines.push(" */");
  lines.push("");
  lines.push("interface Node {");
  lines.push("  x: number;");
  lines.push("  y: number;");
  lines.push("  vx: number;");
  lines.push("  vy: number;");
  lines.push("  radius: number;");
  lines.push("  hue: number;");
  lines.push("  label: string;");
  lines.push("}");
  lines.push("");
  lines.push("interface Edge {");
  lines.push("  from: number;");
  lines.push("  to: number;");
  lines.push("  weight: number;");
  lines.push("}");
  lines.push("");

  lines.push("const CONFIG = {");
  lines.push(`  width: 1920,`);
  lines.push(`  height: 1080,`);
  lines.push(`  nodeCount: ${nodeCount},`);
  lines.push(`  complexity: ${complexity.toFixed(2)},`);
  lines.push(`  palette: ${JSON.stringify(langColors)},`);
  lines.push(`  dampening: 0.98,`);
  lines.push(`  attractionStrength: 0.001,`);
  lines.push(`  repulsionStrength: 500,`);
  lines.push(`  edgeOpacity: 0.3,`);
  lines.push("};");
  lines.push("");

  lines.push("function createNodes(): Node[] {");
  lines.push("  const nodes: Node[] = [];");
  lines.push("  for (let i = 0; i < CONFIG.nodeCount; i++) {");
  lines.push("    const colorEntry = CONFIG.palette[i % CONFIG.palette.length];");
  lines.push("    nodes.push({");
  lines.push("      x: Math.random() * CONFIG.width,");
  lines.push("      y: Math.random() * CONFIG.height,");
  lines.push("      vx: (Math.random() - 0.5) * 2,");
  lines.push("      vy: (Math.random() - 0.5) * 2,");
  lines.push("      radius: 4 + Math.random() * (colorEntry.weight / 10),");
  lines.push("      hue: colorEntry.hue + (Math.random() - 0.5) * 20,");
  lines.push(`      label: colorEntry.name,`);
  lines.push("    });");
  lines.push("  }");
  lines.push("  return nodes;");
  lines.push("}");
  lines.push("");

  lines.push("function createEdges(nodeCount: number): Edge[] {");
  lines.push("  const edges: Edge[] = [];");
  lines.push("  const edgeCount = Math.floor(nodeCount * CONFIG.complexity * 1.5);");
  lines.push("  for (let i = 0; i < edgeCount; i++) {");
  lines.push("    edges.push({");
  lines.push("      from: Math.floor(Math.random() * nodeCount),");
  lines.push("      to: Math.floor(Math.random() * nodeCount),");
  lines.push("      weight: 0.5 + Math.random() * 0.5,");
  lines.push("    });");
  lines.push("  }");
  lines.push("  return edges;");
  lines.push("}");
  lines.push("");

  lines.push("function simulate(nodes: Node[], edges: Edge[]) {");
  lines.push("  // Repulsion between all nodes");
  lines.push("  for (let i = 0; i < nodes.length; i++) {");
  lines.push("    for (let j = i + 1; j < nodes.length; j++) {");
  lines.push("      const dx = nodes[j].x - nodes[i].x;");
  lines.push("      const dy = nodes[j].y - nodes[i].y;");
  lines.push("      const dist = Math.sqrt(dx * dx + dy * dy) + 1;");
  lines.push("      const force = CONFIG.repulsionStrength / (dist * dist);");
  lines.push("      nodes[i].vx -= (dx / dist) * force;");
  lines.push("      nodes[i].vy -= (dy / dist) * force;");
  lines.push("      nodes[j].vx += (dx / dist) * force;");
  lines.push("      nodes[j].vy += (dy / dist) * force;");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  // Attraction along edges");
  lines.push("  for (const edge of edges) {");
  lines.push("    const a = nodes[edge.from];");
  lines.push("    const b = nodes[edge.to];");
  lines.push("    const dx = b.x - a.x;");
  lines.push("    const dy = b.y - a.y;");
  lines.push("    a.vx += dx * CONFIG.attractionStrength * edge.weight;");
  lines.push("    a.vy += dy * CONFIG.attractionStrength * edge.weight;");
  lines.push("    b.vx -= dx * CONFIG.attractionStrength * edge.weight;");
  lines.push("    b.vy -= dy * CONFIG.attractionStrength * edge.weight;");
  lines.push("  }");
  lines.push("");
  lines.push("  // Update positions");
  lines.push("  for (const node of nodes) {");
  lines.push("    node.vx *= CONFIG.dampening;");
  lines.push("    node.vy *= CONFIG.dampening;");
  lines.push("    node.x += node.vx;");
  lines.push("    node.y += node.vy;");
  lines.push("    node.x = Math.max(node.radius, Math.min(CONFIG.width - node.radius, node.x));");
  lines.push("    node.y = Math.max(node.radius, Math.min(CONFIG.height - node.radius, node.y));");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  lines.push("export function renderSketch(canvas: HTMLCanvasElement) {");
  lines.push("  canvas.width = CONFIG.width;");
  lines.push("  canvas.height = CONFIG.height;");
  lines.push("  const ctx2d = canvas.getContext(\"2d\")!;");
  lines.push("  const nodes = createNodes();");
  lines.push("  const edges = createEdges(nodes.length);");
  lines.push("");
  lines.push("  function frame() {");
  lines.push("    simulate(nodes, edges);");
  lines.push("    ctx2d.fillStyle = \"rgba(15, 23, 42, 0.1)\";");
  lines.push("    ctx2d.fillRect(0, 0, CONFIG.width, CONFIG.height);");
  lines.push("");
  lines.push("    // Draw edges");
  lines.push("    for (const edge of edges) {");
  lines.push("      const a = nodes[edge.from];");
  lines.push("      const b = nodes[edge.to];");
  lines.push("      ctx2d.strokeStyle = `hsla(${a.hue}, 60%, 60%, ${CONFIG.edgeOpacity * edge.weight})`;");
  lines.push("      ctx2d.lineWidth = edge.weight;");
  lines.push("      ctx2d.beginPath();");
  lines.push("      ctx2d.moveTo(a.x, a.y);");
  lines.push("      ctx2d.lineTo(b.x, b.y);");
  lines.push("      ctx2d.stroke();");
  lines.push("    }");
  lines.push("");
  lines.push("    // Draw nodes");
  lines.push("    for (const node of nodes) {");
  lines.push("      ctx2d.fillStyle = `hsl(${node.hue}, 70%, 60%)`;");
  lines.push("      ctx2d.beginPath();");
  lines.push("      ctx2d.arc(node.x, node.y, node.radius, 0, Math.PI * 2);");
  lines.push("      ctx2d.fill();");
  lines.push("    }");
  lines.push("");
  lines.push("    requestAnimationFrame(frame);");
  lines.push("  }");
  lines.push("");
  lines.push("  frame();");
  lines.push("}");
  lines.push("");

  lines.push("export { CONFIG, createNodes, createEdges, simulate };");

  // ─── Source File Analysis ────────────────────────────────────
  if (files && files.length > 0) {
    lines.push("");
    lines.push("// ─── Source File Tree ──────────────────────────────────");
    const tree = fileTree(files);
    for (const line of tree.slice(0, 20)) {
      lines.push(`// ${line}`);
    }
  }

  return {
    path: "generative-sketch.ts",
    content: lines.join("\n"),
    content_type: "text/typescript",
    program: "algorithmic",
    description: `Force-directed generative sketch visualizing ${id.name} project structure`,
  };
}

// ─── parameter-pack.json ────────────────────────────────────────

export function generateParameterPack(ctx: ContextMap, files?: SourceFile[]): GeneratedFile {
  const id = ctx.project_identity;
  const languages = ctx.detection.languages;
  const score = ctx.architecture_signals.separation_score;
  const hotspots = ctx.dependency_graph.hotspots;

  const pack = {
    project: id.name,
    generated_at: new Date().toISOString(),
    description: "Parameter sets for generative visualizations derived from project metrics",
    parameters: {
      structure: {
        node_count: Math.max(5, ctx.entry_points.length * 3 + hotspots.length * 2),
        edge_density: Math.min(1, score / 100),
        cluster_count: Math.max(1, ctx.architecture_signals.layer_boundaries.length),
        symmetry: score > 70 ? "radial" : score > 40 ? "bilateral" : "organic",
      },
      color: {
        palette: languages.slice(0, 5).map((l, i) => {
          const hues = [220, 280, 340, 160, 40];
          return {
            name: l.name,
            hue: hues[i % hues.length],
            saturation: 60 + (l.loc_percent / 100) * 20,
            lightness: 50 + (l.loc_percent / 100) * 15,
            weight: l.loc_percent,
          };
        }),
        background: { h: 220, s: 40, l: 8 },
        accent: { h: 240, s: 80, l: 65 },
      },
      motion: {
        speed: score > 60 ? 0.5 : 1.0,
        dampening: 0.98,
        attraction: 0.001,
        repulsion: 500,
        turbulence: score > 70 ? 0.1 : 0.3,
      },
      render: {
        width: 1920,
        height: 1080,
        fps: 60,
        trail_opacity: 0.1,
        node_min_radius: 3,
        node_max_radius: 12,
        edge_opacity: 0.3,
        glow: true,
        anti_alias: true,
      },
    },
    presets: [
      {
        name: "calm",
        overrides: { "motion.speed": 0.3, "motion.turbulence": 0.05, "render.trail_opacity": 0.05 },
      },
      {
        name: "energetic",
        overrides: { "motion.speed": 1.5, "motion.turbulence": 0.5, "render.trail_opacity": 0.2 },
      },
      {
        name: "minimal",
        overrides: { "structure.node_count": 10, "render.edge_opacity": 0.1, "render.glow": false },
      },
    ],
    source_files_count: null as number | null,
  };

  // ─── Source File Analysis ────────────────────────────────────
  if (files && files.length > 0) {
    pack.source_files_count = files.length;
  }

  return {
    path: "parameter-pack.json",
    content: JSON.stringify(pack, null, 2),
    content_type: "application/json",
    program: "algorithmic",
    description: "Parameter sets for generative art derived from project architecture metrics",
  };
}

// ─── collection-map.md ──────────────────────────────────────────

export function generateCollectionMap(ctx: ContextMap, files?: SourceFile[]): GeneratedFile {
  const id = ctx.project_identity;
  const languages = ctx.detection.languages;
  const patterns = ctx.architecture_signals.patterns_detected;
  const layers = ctx.architecture_signals.layer_boundaries;
  const hotspots = ctx.dependency_graph.hotspots;

  const lines: string[] = [];

  lines.push(`# Collection Map — ${id.name}`);
  lines.push("");
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push("");

  lines.push("## Collection Overview");
  lines.push("");
  lines.push("A curated set of generative art pieces derived from the structure,");
  lines.push(`metrics, and architecture of ${id.name}.`);
  lines.push("");

  if (ctx.ai_context.project_summary) {
    lines.push("## Project Summary");
    lines.push("");
    lines.push(ctx.ai_context.project_summary);
    lines.push("");
  }

  // Framework stack reference
  if (ctx.detection.frameworks.length > 0) {
    lines.push("## Detected Stack");
    lines.push("");
    lines.push("| Framework | Version | Confidence |");
    lines.push("|-----------|---------|------------|");
    for (const fw of ctx.detection.frameworks) {
      lines.push(`| ${fw.name} | ${fw.version ?? "—"} | ${(fw.confidence * 100).toFixed(0)}% |`);
    }
    lines.push("");
  }

  lines.push("## Pieces");
  lines.push("");

  // Piece 1: Network Graph
  lines.push("### 1. Dependency Network");
  lines.push("");
  lines.push("- **Type**: Force-directed graph");
  lines.push(`- **Nodes**: ${ctx.entry_points.length + hotspots.length} (entry points + hotspots)`);
  lines.push(`- **Edges**: Based on import graph density`);
  lines.push("- **Color mapping**: Language → hue");
  lines.push("- **Animation**: Continuous force simulation");
  lines.push("- **Source**: generative-sketch.ts");
  lines.push("");

  // Piece 2: Language Ring
  lines.push("### 2. Language Ring");
  lines.push("");
  lines.push("- **Type**: Concentric ring visualization");
  lines.push("- **Rings**: One per language, radius ∝ LOC percentage");
  for (const lang of languages) {
    lines.push(`  - ${lang.name}: ${lang.loc_percent}% → radius ${Math.round(lang.loc_percent * 3)}px`);
  }
  lines.push("- **Animation**: Slow rotation, pulse on interaction");
  lines.push("");

  // Piece 3: Architecture Terrain
  lines.push("### 3. Architecture Terrain");
  lines.push("");
  lines.push("- **Type**: Topographic height map");
  lines.push(`- **Elevation**: Architecture score ${ctx.architecture_signals.separation_score}/100 → height multiplier`);
  if (patterns.length > 0) {
    lines.push(`- **Ridges**: ${patterns.join(", ")}`);
  }
  if (layers.length > 0) {
    lines.push("- **Strata**:");
    for (const l of layers) {
      lines.push(`  - ${l.layer}: ${l.directories.join(", ")}`);
    }
  }
  lines.push("- **Animation**: Perlin noise drift");
  lines.push("");

  // Piece 4: Hotspot Constellation
  lines.push("### 4. Hotspot Constellation");
  lines.push("");
  lines.push("- **Type**: Star field / particle system");
  lines.push(`- **Stars**: ${hotspots.length} hotspot files`);
  if (hotspots.length > 0) {
    lines.push("- **Brightest stars (highest risk)**:");
    for (const h of hotspots.slice(0, 5)) {
      lines.push(`  - \`${h.path}\` (risk: ${h.risk_score.toFixed(1)}, connections: ${h.inbound_count + h.outbound_count})`);
    }
  }
  lines.push("- **Brightness**: risk_score mapped to luminosity");
  lines.push("- **Size**: inbound + outbound connections");
  lines.push("- **Animation**: Twinkling, slow drift");
  lines.push("");

  lines.push("## Collection Metadata");
  lines.push("");
  lines.push(`| Property | Value |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Total Pieces | 4 |`);
  lines.push(`| Source Project | ${id.name} |`);
  lines.push(`| Data Points | ${ctx.entry_points.length + hotspots.length + languages.length + patterns.length} |`);
  lines.push(`| Domain Models | ${ctx.domain_models.length} |`);
  lines.push(`| Routes | ${ctx.routes.length} |`);
  lines.push(`| Total Files | ${ctx.structure.total_files} |`);
  lines.push(`| Total LOC | ${ctx.structure.total_loc} |`);
  lines.push(`| Render Target | Canvas 2D / WebGL |`);
  lines.push(`| Parameter Pack | parameter-pack.json |`);
  lines.push("");

  // ─── Source File Analysis ────────────────────────────────────
  if (files && files.length > 0) {
    lines.push("## Source File Tree");
    lines.push("");
    lines.push("```");
    const tree = fileTree(files);
    for (const line of tree.slice(0, 25)) {
      lines.push(line);
    }
    lines.push("```");
    lines.push("");
  }

  return {
    path: "collection-map.md",
    content: lines.join("\n"),
    content_type: "text/markdown",
    program: "algorithmic",
    description: "Map of generative art collection pieces derived from project architecture",
  };
}

// ─── export-manifest.yaml ───────────────────────────────────────

export function generateExportManifest(ctx: ContextMap, profile: RepoProfile, files?: SourceFile[]): GeneratedFile {
  const id = ctx.project_identity;

  const lines: string[] = [];

  lines.push("# Export Manifest");
  lines.push(`# Project: ${id.name}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("manifest:");
  lines.push(`  project: ${JSON.stringify(id.name)}`);
  lines.push("  version: \"1.0\"");
  lines.push(`  total_artifacts: 4`);
  lines.push("");

  lines.push("  artifacts:");

  lines.push("    - id: generative-sketch");
  lines.push("      file: generative-sketch.ts");
  lines.push("      type: code");
  lines.push("      format: typescript");
  lines.push("      description: Force-directed graph animation");
  lines.push("      exports:");
  lines.push("        - format: html");
  lines.push("          resolution: 1920x1080");
  lines.push("          self_contained: true");
  lines.push("        - format: mp4");
  lines.push("          resolution: 1920x1080");
  lines.push("          duration: 30s");
  lines.push("          fps: 60");
  lines.push("        - format: gif");
  lines.push("          resolution: 800x450");
  lines.push("          duration: 5s");
  lines.push("        - format: png_sequence");
  lines.push("          resolution: 1920x1080");
  lines.push("          frame_count: 300");
  lines.push("");

  lines.push("    - id: parameter-pack");
  lines.push("      file: parameter-pack.json");
  lines.push("      type: data");
  lines.push("      format: json");
  lines.push("      description: Tunable parameters for all generative pieces");
  lines.push("      exports:");
  lines.push("        - format: json");
  lines.push("          description: Raw parameter data");
  lines.push("        - format: yaml");
  lines.push("          description: Human-readable parameter data");
  lines.push("");

  lines.push("    - id: collection-map");
  lines.push("      file: collection-map.md");
  lines.push("      type: documentation");
  lines.push("      format: markdown");
  lines.push("      description: Collection overview with piece descriptions");
  lines.push("      exports:");
  lines.push("        - format: md");
  lines.push("          description: Markdown document");
  lines.push("        - format: pdf");
  lines.push("          description: Print-ready catalog");
  lines.push("");

  lines.push("    - id: export-manifest");
  lines.push("      file: export-manifest.yaml");
  lines.push("      type: metadata");
  lines.push("      format: yaml");
  lines.push("      description: This manifest file");
  lines.push("");

  lines.push("  render_pipeline:");
  lines.push("    steps:");
  lines.push("      - name: load_parameters");
  lines.push("        input: parameter-pack.json");
  lines.push("        description: Load and validate parameter sets");
  lines.push("      - name: generate_frames");
  lines.push("        input: generative-sketch.ts");
  lines.push("        description: Run simulation and capture frames");
  lines.push("      - name: encode_video");
  lines.push("        codec: h264");
  lines.push("        description: Encode frame sequence to video");
  lines.push("      - name: export_stills");
  lines.push("        frames: [0, 60, 150, 299]");
  lines.push("        description: Export key frames as PNG stills");
  lines.push("");

  lines.push("  dependencies:");
  lines.push("    runtime:");
  lines.push("      - name: canvas");
  lines.push("        version: \">=2.0\"");
  lines.push("        purpose: Server-side Canvas rendering");
  lines.push("      - name: ffmpeg");
  lines.push("        version: \">=5.0\"");
  lines.push("        purpose: Video encoding");
  lines.push("    optional:");
  lines.push("      - name: sharp");
  lines.push("        purpose: Image optimization");
  lines.push("      - name: puppeteer");
  lines.push("        purpose: Browser-based rendering");
  lines.push("");

  // ─── Source File Analysis ────────────────────────────────────
  if (files && files.length > 0) {
    const imageFiles = findFiles(files, ["*.png", "*.jpg", "*.svg", "*.gif", "*.webp"]);
    if (imageFiles.length > 0) {
      lines.push("  source_assets:");
      for (const img of imageFiles.slice(0, 10)) {
        lines.push(`    - path: ${JSON.stringify(img.path)}`);
        lines.push(`      size: ${img.size}`);
      }
      lines.push("");
    }
  }

  return {
    path: "export-manifest.yaml",
    content: lines.join("\n"),
    content_type: "text/yaml",
    program: "algorithmic",
    description: "Export manifest with artifacts, render pipeline, and dependency requirements",
  };
}

// ─── variation-matrix.json ──────────────────────────────────────

export function generateVariationMatrix(ctx: ContextMap, files?: SourceFile[]): GeneratedFile {
  const id = ctx.project_identity;
  const frameworks = ctx.detection.frameworks;
  const languages = ctx.detection.languages;
  const hotspots = ctx.dependency_graph.hotspots;
  const abstractions = ctx.ai_context.key_abstractions;
  const deps = ctx.dependency_graph.external_dependencies;

  // Build parameter definitions based on project characteristics
  const parameters: Record<string, unknown>[] = [];

  // Color parameter from project language palette
  const langColors: Record<string, string> = {
    TypeScript: "#3178C6", JavaScript: "#F7DF1E", Python: "#3776AB",
    Rust: "#DEA584", Go: "#00ADD8", Java: "#ED8B00", Ruby: "#CC342D",
    "C#": "#239120", Swift: "#FA7343", Kotlin: "#7F52FF",
  };
  const projectColors = languages.map(l => langColors[l.name] ?? "#64748B").slice(0, 4);
  parameters.push({
    name: "primary_hue",
    type: "color",
    values: projectColors.length > 0 ? projectColors : ["#2563EB", "#7C3AED", "#06B6D4", "#16A34A"],
    description: "Base color derived from project language palette",
  });

  // Complexity parameter from architecture signals
  parameters.push({
    name: "complexity",
    type: "float",
    range: [0.1, 1.0],
    steps: 5,
    values: [0.1, 0.3, 0.5, 0.7, 1.0],
    description: "Visual complexity scaling factor",
  });

  // Density parameter from file count
  const totalFiles = languages.reduce((t, l) => t + l.file_count, 0);
  const densityRange = totalFiles > 200 ? [50, 100, 200, 400] : [10, 25, 50, 100];
  parameters.push({
    name: "element_count",
    type: "integer",
    values: densityRange,
    description: `Element density based on project scale (${totalFiles} files)`,
  });

  // Layout parameter from framework detection
  const layoutVariants = ["grid", "radial", "force-directed", "treemap"];
  if (frameworks.some(f => f.name.toLowerCase().includes("react") || f.name.toLowerCase().includes("vue"))) {
    layoutVariants.push("component-tree");
  }
  parameters.push({
    name: "layout",
    type: "enum",
    values: layoutVariants,
    description: "Spatial arrangement algorithm",
  });

  // Seed values for reproducibility
  const seedBase = id.name.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
  const seeds = Array.from({ length: 6 }, (_, i) => seedBase * (i + 1) + 42);
  parameters.push({
    name: "seed",
    type: "integer",
    values: seeds,
    description: `Deterministic seeds derived from project name "${id.name}"`,
  });

  // Generate variation grid (top 24 combinations)
  const variations: Record<string, unknown>[] = [];
  let variationId = 0;
  for (const color of (parameters[0].values as string[]).slice(0, 2)) {
    for (const complexity of [0.3, 0.7]) {
      for (const layout of layoutVariants.slice(0, 3)) {
        variationId++;
        variations.push({
          id: `var_${String(variationId).padStart(3, "0")}`,
          params: {
            primary_hue: color,
            complexity,
            element_count: densityRange[Math.floor(densityRange.length / 2)],
            layout,
            seed: seeds[variationId % seeds.length],
          },
          thumbnail: `thumbnails/var_${String(variationId).padStart(3, "0")}.png`,
          tags: [
            complexity > 0.5 ? "complex" : "minimal",
            layout,
          ],
        });
      }
    }
  }

  // Hotspot-derived feature highlights
  const featureHighlights = hotspots.slice(0, 5).map(h => ({
    source_file: h.path,
    risk_score: h.risk_score,
    visual_weight: Math.min(h.risk_score / 10, 1.0),
    suggested_emphasis: h.risk_score > 7 ? "glow" : h.risk_score > 4 ? "border" : "subtle",
  }));

  // Abstraction-derived labels
  const labelOverlays = abstractions.slice(0, 6).map((a, i) => ({
    text: a,
    position: i < 3 ? "top" : "bottom",
    style: i === 0 ? "hero" : "caption",
  }));

  const matrix = {
    project: id.name,
    generated: new Date().toISOString(),
    parameters,
    variation_count: variations.length,
    variations,
    feature_highlights: featureHighlights,
    label_overlays: labelOverlays,
    render_config: {
      output_format: "png",
      resolution: { width: 1920, height: 1080 },
      thumbnail_size: { width: 320, height: 180 },
      anti_aliasing: true,
      background: "transparent",
    },
    batch_export: {
      parallel: 4,
      naming: "var_{id}_{layout}_{complexity}",
      formats: ["png", "svg", "webp"],
    },
    source_file_count: null as number | null,
  };

  // ─── Source File Analysis ────────────────────────────────────
  if (files && files.length > 0) {
    matrix.source_file_count = files.length;
  }

  return {
    path: "variation-matrix.json",
    content: JSON.stringify(matrix, null, 2),
    content_type: "application/json",
    program: "algorithmic",
    description: "Parameter variation matrix with seeds, render configs, and thumbnail grid",
  };
}
