import type { ContextMap, RepoProfile } from "@axis/context-engine";
import type { GeneratedFile } from "./types.js";

export function generateAgentsMD(ctx: ContextMap): GeneratedFile {
  const id = ctx.project_identity;
  const ai = ctx.ai_context;
  const lines: string[] = [];

  lines.push(`# AGENTS.md — ${id.name}`);
  lines.push("");
  lines.push("## Project Context");
  lines.push("");
  lines.push(`This is a **${id.type.replace(/_/g, " ")}** built with **${id.primary_language}**.`);
  if (id.description) lines.push(`${id.description}`);
  lines.push("");

  // Frameworks
  if (ctx.detection.frameworks.length > 0) {
    lines.push("### Stack");
    lines.push("");
    for (const fw of ctx.detection.frameworks) {
      lines.push(`- ${fw.name}${fw.version ? ` ${fw.version}` : ""}`);
    }
    lines.push("");
  }

  // Architecture
  if (ctx.architecture_signals.patterns_detected.length > 0) {
    lines.push("### Architecture");
    lines.push("");
    for (const p of ctx.architecture_signals.patterns_detected) {
      lines.push(`- ${p.replace(/_/g, " ")}`);
    }
    lines.push("");
  }

  // Conventions
  if (ai.conventions.length > 0) {
    lines.push("### Conventions");
    lines.push("");
    for (const c of ai.conventions) {
      lines.push(`- ${c}`);
    }
    lines.push("");
  }

  // Key Abstractions
  if (ai.key_abstractions.length > 0) {
    lines.push("### Key Directories");
    lines.push("");
    for (const a of ai.key_abstractions) {
      lines.push(`- ${a}`);
    }
    lines.push("");
  }

  // Routes
  if (ctx.routes.length > 0) {
    lines.push("### Routes");
    lines.push("");
    for (const r of ctx.routes) {
      lines.push(`- \`${r.method} ${r.path}\` → ${r.source_file}`);
    }
    lines.push("");
  }

  // Agent instructions
  lines.push("## Agent Instructions");
  lines.push("");
  lines.push("When working in this codebase:");
  lines.push("");

  // Language-specific rules
  if (id.primary_language === "TypeScript" || id.primary_language === "JavaScript") {
    lines.push("- Use strict TypeScript. Avoid `any` types.");
    if (ctx.detection.frameworks.some(f => f.name === "Next.js")) {
      lines.push("- Follow Next.js App Router conventions. Use `app/` directory structure.");
      lines.push("- Server Components by default. Add `'use client'` only when needed.");
    }
    if (ctx.detection.frameworks.some(f => f.name === "React"))
      lines.push("- Prefer functional components with hooks over class components.");
    if (ctx.detection.frameworks.some(f => f.name === "Tailwind CSS"))
      lines.push("- Use Tailwind utility classes. Avoid custom CSS unless extending the design system.");
    if (ctx.detection.frameworks.some(f => f.name === "Prisma"))
      lines.push("- Use Prisma client for database access. Keep schema.prisma as source of truth.");
  }
  if (id.primary_language === "Python") {
    lines.push("- Follow PEP 8 conventions.");
    if (ctx.detection.frameworks.some(f => f.name === "Django"))
      lines.push("- Follow Django project structure conventions.");
    if (ctx.detection.frameworks.some(f => f.name === "FastAPI"))
      lines.push("- Use Pydantic models for request/response validation.");
  }

  // Testing
  if (ctx.detection.test_frameworks.length > 0) {
    lines.push(`- Run tests with ${ctx.detection.test_frameworks[0]} before committing.`);
  }

  // Package manager
  if (ctx.detection.package_managers.length > 0) {
    const pm = ctx.detection.package_managers[0];
    lines.push(`- Use \`${pm}\` for dependency management. Do not mix package managers.`);
  }

  lines.push("");

  // Warnings
  if (ai.warnings.length > 0) {
    lines.push("## Known Issues");
    lines.push("");
    for (const w of ai.warnings) {
      lines.push(`- ${w}`);
    }
    lines.push("");
  }

  // Layer boundaries
  if (ctx.architecture_signals.layer_boundaries.length > 0) {
    lines.push("## Architecture Boundaries");
    lines.push("");
    lines.push("Respect these layer separations:");
    lines.push("");
    for (const l of ctx.architecture_signals.layer_boundaries) {
      lines.push(`- **${l.layer}**: ${l.directories.join(", ")}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Axis Skills*");
  lines.push("");

  return {
    path: "AGENTS.md",
    content: lines.join("\n"),
    content_type: "text/markdown",
    program: "skills",
    description: "AI agent instructions tailored to this project's stack and conventions",
  };
}

export function generateClaudeMD(ctx: ContextMap): GeneratedFile {
  const id = ctx.project_identity;
  const ai = ctx.ai_context;
  const lines: string[] = [];

  lines.push(`# CLAUDE.md — ${id.name}`);
  lines.push("");
  lines.push("## Project Overview");
  lines.push("");
  lines.push(ai.project_summary);
  lines.push("");

  // Build & test commands
  lines.push("## Commands");
  lines.push("");
  const pm = ctx.detection.package_managers[0] ?? "npm";
  lines.push(`- **Install:** \`${pm} install\``);
  if (ctx.detection.build_tools.length > 0)
    lines.push(`- **Build:** \`${pm} run build\``);
  if (ctx.detection.test_frameworks.length > 0)
    lines.push(`- **Test:** \`${pm} test\``);
  lines.push(`- **Dev:** \`${pm} run dev\``);
  if (ctx.detection.frameworks.some(f => f.name === "Prisma"))
    lines.push(`- **DB Migrate:** \`${pm === "npx" ? "npx" : `${pm} exec`} prisma migrate dev\``);
  lines.push("");

  // Stack
  lines.push("## Stack");
  lines.push("");
  for (const fw of ctx.detection.frameworks) {
    lines.push(`- ${fw.name}${fw.version ? ` ${fw.version}` : ""}`);
  }
  if (ctx.detection.ci_platform) lines.push(`- CI: ${ctx.detection.ci_platform}`);
  if (ctx.detection.deployment_target) lines.push(`- Deploy: ${ctx.detection.deployment_target}`);
  lines.push("");

  // Structure
  lines.push("## Structure");
  lines.push("");
  for (const a of ai.key_abstractions) {
    lines.push(`- ${a}`);
  }
  lines.push("");

  // Conventions
  if (ai.conventions.length > 0) {
    lines.push("## Conventions");
    lines.push("");
    for (const c of ai.conventions) {
      lines.push(`- ${c}`);
    }
    lines.push("");
  }

  // Don'ts
  lines.push("## Do NOT");
  lines.push("");
  lines.push("- Do not add dependencies without discussion");
  lines.push("- Do not change the framework or architecture pattern");
  lines.push("- Do not bypass TypeScript strict mode");
  if (ctx.detection.frameworks.some(f => f.name === "Prisma"))
    lines.push("- Do not write raw SQL — use Prisma Client");
  if (ctx.detection.frameworks.some(f => f.name === "React"))
    lines.push("- Do not use class components");
  lines.push("");

  if (ai.warnings.length > 0) {
    lines.push("## Warnings");
    lines.push("");
    for (const w of ai.warnings) {
      lines.push(`- ${w}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Axis Skills*");
  lines.push("");

  return {
    path: "CLAUDE.md",
    content: lines.join("\n"),
    content_type: "text/markdown",
    program: "skills",
    description: "Claude-specific project instructions with commands and conventions",
  };
}

export function generateCursorRules(ctx: ContextMap): GeneratedFile {
  const id = ctx.project_identity;
  const rules: string[] = [];

  rules.push(`# .cursorrules — ${id.name}`);
  rules.push("#");
  rules.push(`# ${id.type.replace(/_/g, " ")} | ${id.primary_language}`);
  rules.push("#");

  // Stack summary
  const frameworks = ctx.detection.frameworks.map(f => f.name).join(", ");
  if (frameworks) rules.push(`# Stack: ${frameworks}`);
  rules.push("");

  // Rules
  rules.push("# === General ===");
  rules.push(`primary_language = "${id.primary_language}"`);
  rules.push(`project_type = "${id.type}"`);
  rules.push("");

  // Framework-specific rules
  if (ctx.detection.frameworks.some(f => f.name === "Next.js")) {
    rules.push("# === Next.js ===");
    rules.push('routing = "app_router"');
    rules.push('default_component_type = "server"');
    rules.push('client_directive = "use client — only when client interactivity needed"');
    rules.push("");
  }

  if (ctx.detection.frameworks.some(f => f.name === "React")) {
    rules.push("# === React ===");
    rules.push('component_style = "functional"');
    rules.push('state_management = "hooks"');
    rules.push("class_components = false");
    rules.push("");
  }

  if (ctx.detection.frameworks.some(f => f.name === "Tailwind CSS")) {
    rules.push("# === Styling ===");
    rules.push('css_framework = "tailwind"');
    rules.push("custom_css = false");
    rules.push('class_strategy = "utility-first"');
    rules.push("");
  }

  if (ctx.detection.frameworks.some(f => f.name === "Prisma")) {
    rules.push("# === Database ===");
    rules.push('orm = "prisma"');
    rules.push("raw_sql = false");
    rules.push('schema_location = "prisma/schema.prisma"');
    rules.push("");
  }

  // Testing
  if (ctx.detection.test_frameworks.length > 0) {
    rules.push("# === Testing ===");
    rules.push(`test_framework = "${ctx.detection.test_frameworks[0]}"`);
    rules.push("test_before_commit = true");
    rules.push("");
  }

  // Package manager
  if (ctx.detection.package_managers.length > 0) {
    rules.push("# === Tooling ===");
    rules.push(`package_manager = "${ctx.detection.package_managers[0]}"`);
    if (ctx.detection.ci_platform) rules.push(`ci = "${ctx.detection.ci_platform}"`);
    rules.push("");
  }

  // Architecture
  rules.push("# === Architecture Boundaries ===");
  for (const layer of ctx.architecture_signals.layer_boundaries) {
    rules.push(`# ${layer.layer}: ${layer.directories.join(", ")}`);
  }
  rules.push("");

  // Conventions
  const ai = ctx.ai_context;
  if (ai.conventions.length > 0) {
    rules.push("# === Detected Conventions ===");
    for (const c of ai.conventions) {
      rules.push(`# - ${c}`);
    }
    rules.push("");
  }

  return {
    path: ".cursorrules",
    content: rules.join("\n"),
    content_type: "text/plain",
    program: "skills",
    description: "Cursor IDE rules derived from project detection and conventions",
  };
}
