/**
 * Embeddable context snippet for avery-pay-platform
 * Generated by Axis' Iliad
 * Drop this into any AI prompt to inject project context
 */

export const PROJECT_CONTEXT = {
  name: "avery-pay-platform",
  type: "static_site",
  language: "Go",
  description: "PAI'D is **two systems in one repo**:",
} as const;

export const CONVENTIONS = [
  "TypeScript strict mode",
] as const;

export const WARNINGS = [
  "No CI/CD pipeline detected",
  "No lockfile found — dependency versions may be inconsistent",
] as const;

export const KEY_ABSTRACTIONS = [
  "go-backend/ (project_directory)",
  "frontend/ (project_directory)",
  "trust-fabric-frontend/ (project_directory)",
  "archive/ (project_directory)",
  "src/ (application_source)",
  "wedge_portfolio/ (project_directory)",
  "docs/ (documentation)",
  "scripts/ (build_scripts)",
] as const;

/**
 * Inject into an AI prompt as a system-level context block.
 * Usage: embedProjectContext() returns a formatted string.
 */
export function embedProjectContext(): string {
  const sections = [
    `# Project: ${PROJECT_CONTEXT.name}`,
    `Type: ${PROJECT_CONTEXT.type} | Language: ${PROJECT_CONTEXT.language}`,
    `Description: ${PROJECT_CONTEXT.description}`,
    "",
    "## Conventions",
    ...CONVENTIONS.map(c => `- ${c}`),
    "",
    "## Warnings",
    ...WARNINGS.map(w => `- ${w}`),
    "",
    "## Key Abstractions",
    ...KEY_ABSTRACTIONS.map(a => `- ${a}`),
  ];
  return sections.join("\n");
}